Build a Multilingual News app using Sveltekit with Directus i18n API
directus-labs/guest-authoring pull request #131
Opened 2024-04-11 21:12 UTC by icode247

2024-04-24 19:27 UTC, phazonoverload requested changes
I've reviewed everything up until the part where you start on the Svelte application. Could you make sure you're following al lthe best practice from [this post](https://docs.directus.io/blog/getting-started-directus-sveltekit.html#create-a-wrapper-for-the-sdk) especially the bit I linked about creating a wrapper.

Could you please also remove all CSS from this project as it's not helping teach the core concepts.

Once you address the changes in the first half, and bring this more in like with the other SvelteKit post, request a re-review and I'll get right back on it. Thanks for your patience while I get around to providing this initial review.

2024-04-24 19:27 UTC, phazonoverload commented on multilingual-news-app-using-sveltekit-with-directus/index.md
> +The code for this tutorial is available on my [GitHub repository](https://github.com/icode247/directus-i18n-app); feel free to clone it to follow along.
```suggestion
## Before You Start

You will need:

- [Node.js v20.11.1](https://nodejs.org/) or later.
- A code editor on your computer.
- A Directus project - follow our [quickstart guide](https://docs.directus.io/getting-started/quickstart) if you don't already have one.
- Some knowledge of React and Svelte.

The code for this tutorial is available on my [GitHub repository](https://github.com/icode247/directus-i18n-app).
```

2024-04-24 19:27 UTC, phazonoverload commented on multilingual-news-app-using-sveltekit-with-directus/index.md
> +With the Directus i18n API, you can build multilingual applications or websites that serve localized content to users based on their preferred language or region.
Remove this - I don't think it adds much that hasn't already been said.

2024-04-24 19:27 UTC, phazonoverload commented on multilingual-news-app-using-sveltekit-with-directus/index.md
> +```
````suggestion
Let's start by setting up a new Svelte project using the [degit scaffolding tool](https://github.com/Rich-Harris/degit):

```
npx degit sveltejs/template directus-i18n-app
```

Install the required dependencies:

```
cd directus-i18n-app 
npm install
npm install @directus/sdk
npm install --save-dev svelte-routing
```

In the `src/libs` directory, create a `directus.js` file to create and export a Directus SDK instance:

```
import { createDirectus, rest } from '@directus/sdk';
const directus = createDirectus('<YOUR DIRECTUS URL>').with(rest());
export default directus;
```

Be sure to provide your real project URL.
````

This should be a continuation of 'Before You Start'. As you can see, we've brought all of the dependency installation into a single instruction to make this more concise. The SDK install has also been moved here as it's a related step.

I've also added the boring boilerplate of setting up the SDK to this section.

2024-04-24 19:27 UTC, phazonoverload commented on multilingual-news-app-using-sveltekit-with-directus/index.md
> +
```suggestion
## Designing a Data Model

In the Directus Data Studio, navigate to Settings -> Data Model and create a new collection called `news`:

- `id` (Primary Key Field, Type: Auto-incremented Integer)
- `author` (Type: String, Interface: Input)
- `cover` (Type: Image)

Create a collection called `languages`:

- `code` (Primary Key Field, Type: Manually entered string )
- `name` (Type: String, Interface: Input)
- `direction` (Type: String, Interface: Dropdown, Options: `ltr` and `rtl`. Default Value: `ltr`)

The `direction` field enables support for languages that read right to left.

To enable content translation in your `news` collection, add a new One to Many `translations` field with the `languages` collection. Select `name` as the **Language Indicator Field** and `direction` as the **Language Direction Field**.

![Creating Directus translations collection](./creating-news-translation-collection.png)

Once you save, a new collection named `news_translations` will be created for you. In the `news_translations` collection, you will add the fields that need translations. 

Add the following fields to the `news_translations` collection:

- `title` (Type: String, Interface: Input)
- `slug` (Type: String, Interface: Input)
- `body` (Type: Text, Interface: WYSIWYG)

Add each language you want to support as items in the `languages` collection. 

![Creating new entries in the languages collections](./languages-entries.png)

The item page for the `news` collection now includes a translations interface.

![Creating new entries in the news collections](./news-translation-entries.png)

Allow the Public role to read the `news`, `languages` and `news_translations` collections in the Access Control settings to ensure the frontend can access these fields.
```

I've made some suggestions to make this much more succinct, but I want to point out that you're shifting from second person (you) to first person plural (our) pronouns. This is good to keep an eye on as you write more content - stay consistent. I've changed them to second person for you.

2024-04-24 19:27 UTC, phazonoverload commented on multilingual-news-app-using-sveltekit-with-directus/index.md
> +```
Remove

2024-04-26 17:57 UTC, icode247 commented
Hi @phazonoverload,
The `readItem` function throws:

```
 errors: [
    {
      message: "You don't have permission to access this.",
      extensions: [Object]
    }
  ],
```

But I have given read permission to the collections. Also to works with the `readItems` function.

2024-04-30 10:00 UTC, icode247 commented
Hi @phazonoverload,
I have worked on the requested changes. Please take another look.

2024-05-01 05:45 UTC, phazonoverload approved these changes
Thank you for writing this, and we are happy to consider it done in it's current state. My team will schedule it in to be published. 

This repo is just for authoring/reviewing - the actual piece will be published via a Directus project, so we'll take it from here. I'll close this issue to keep the main branch clean, but this is a acceptance of your work.

Could you email me at [devrel@directus.io](mailto:devrel@directus.io) and we'll share what we need to get you paid. Thanks!

2024-05-01 05:45 UTC, closed without merging