How to Build CRUD Application Using Directus and Flutter
directus-labs/guest-authoring pull request #140
Opened 2024-04-17 18:52 UTC by Claradev32

First draft

2024-04-24 19:02 UTC, phazonoverload requested changes
Good post. Some comments that need addressing. There is still some work needed to bring it to the standard format. Please also use the consistent `directory` term throughout.

2024-04-24 19:02 UTC, phazonoverload commented on crud-with-flutter-and-directus/index.md
> +Now that you've acquired this knowledge, what would you like to build next with the Directus CMS? Perhaps you can improve on this project by adding authentication to protect the application, and form
```suggestion
Throughout this tutorial, you've learned how to build a Flutter application that uses data from a Directus project. We started by creating a new project, set up environment variables and everything we need to call Directus. We then created pages and posts collections in Directus and integrated them with the the Flutter.
```

2024-04-25 17:37 UTC, Claradev32 commented
Hi @phazonoverload,

I have worked on your reviews.

Thank you.

2024-04-26 10:16 UTC, phazonoverload commented
All of my review comments were not incorporated. Please can you make sure they are accurately and then request a re-review.

2024-04-26 18:24 UTC, Claradev32 commented on crud-with-flutter-and-directus/index.md
> +![Adding entries to Directus collection](./Screenshot%202024-04-17%20at%2011.26.32.png)
Done

2024-04-26 19:07 UTC, Claradev32 commented
@phazonoverload I've addressed the feedback and made the requested changes. Could you please take another look?

2024-04-30 14:11 UTC, phazonoverload commented
Thank you for writing this, and we are happy to consider it done in it's current state. My team will schedule it in to be published. 

This repo is just for authoring/reviewing - the actual piece will be published via a Directus project, so we'll take it from here. I'll close this issue to keep the main branch clean, but this is a acceptance of your work.

Could you email me at [devrel@directus.io](mailto:devrel@directus.io) and we'll share what we need to get you paid. Thanks!

2024-04-30 14:11 UTC, closed without merging