Build A GitHub Repository Tracker With Directus Flow
directus-labs/guest-authoring pull request #278
Opened 2024-06-21 14:34 UTC by psalmuelle

Hi @phazonoverload,

I am done with the first draft and I await your review.

This PR is for issue #173 

Thank you!

2024-07-02 08:57 UTC, phazonoverload requested changes
Lovely post - some suggestions and comments for you to respond to. Only other ask I have is to remove the "name" from each email template.

2024-07-02 08:57 UTC, phazonoverload commented on Build A GitHub Repository Tracker With Directus Flow/github_repository_tracker.md
> +description: "Learn how to keep track of changes in a GitHub repository in your Directus project."
```suggestion
title: "Tracking GitHub Issues and Pull Requests with Directus Automate"
description: "Learn how to use Directus Automate to keep track of new issues, pull requests, and comments in a GitHub repository."
```

2024-07-02 08:57 UTC, phazonoverload commented on Build A GitHub Repository Tracker With Directus Flow/github_repository_tracker.md
> +:::
```suggestion
In this tutorial, you will learn how to track events, such as new issues and pull requests, in a GitHub repository using Directus Automate. By the end of this article, you will have created a repository tracker that sends alerts via email and in-app notifications.

## Before You Start

You will need:

- A Directus project - Create a project by following this [quickstart guide](https://docs.directus.io/getting-started/quickstart.html). Your project will need to be accessible via a public URL so you'll need to host it or use a tunnel to your local instance.
- [A GitHub Account](https://github.com/signup) and admin access to the GitHub repo you want to track.
```

2024-07-02 08:57 UTC, phazonoverload commented on Build A GitHub Repository Tracker With Directus Flow/github_repository_tracker.md
> +![A screenshot of the Flow demonstrating where to find the Trigger URL](flow_setup.png)
```suggestion
## Creating a New Flow

In your Directus project, navigate to **Settings -> Flows** and create a Flow. In the Trigger Setup section, select **Webhook Trigger** so we can receive events from GitHub. Ensure the Webhook Trigger is set to use the `POST` method with Asynchronous mode enabled. Save the Flow and copy the Trigger URL.

![A screenshot of the Flow demonstrating where to find the Trigger URL](flow_setup.png)
```

2024-07-02 08:57 UTC, phazonoverload commented on Build A GitHub Repository Tracker With Directus Flow/github_repository_tracker.md
> +![A screenshot of Activity Logs section on](github_ping.png)
```suggestion
## Setting Up a Webhook on GitHub

GitHub allows developers to create webhooks for both repositories and organizations. A webhook is a web request to an external URL (in this case, Directus) that will be immediately triggered when an event happens such as a new issue being opened in a repository. 

To create a webhook, navigate to the repository or organization you want to track. Go to the **Settings** tab and select **Webhooks** from the menu.

Click on the **Add Webhook** button. Next, paste the Trigger URL from Directus flow into the `Payload URL` field and change the content type to `application/json`.

Select the events that should trigger the webhook. For this tutorial, choose the `Let me select individual events` option and toggle these events:

- Issues
- Issue comments
- Pull requests

Save your settings by clicking the **Add Webhook** button. GitHub will send a ping payload to your Directus project. Confirm the webhook is successful by checking the Activity Logs section in your Flow.

![A screenshot of Activity Logs section in the Flow editor](github_ping.png)
```

A whole bunch of small changes here:
1. Explain what webhooks are
2. Link them back to the project
3. Remove the image of GitHub as it doesn't serve much value

2024-07-02 08:57 UTC, phazonoverload commented on Build A GitHub Repository Tracker With Directus Flow/github_repository_tracker.md
> +The final step is to set up an alert system to notify you or others on the project when any of the selected events occur. Depending on your preference, you can use email or in-app notifications avail
```suggestion
The final step is to set up an alert system to notify you or others on the project when any of the selected events occur. Depending on your preference, you can use email or in-app notifications available as operations in Flows.
```

2024-07-02 08:57 UTC, phazonoverload commented on Build A GitHub Repository Tracker With Directus Flow/github_repository_tracker.md
> +You can view the full issue and its details by following this link: [Link to the issue]($trigger.body.issue.html_url).
Make sure to test these - I think this needs the {{}} to be valid

2024-07-02 08:57 UTC, phazonoverload commented on Build A GitHub Repository Tracker With Directus Flow/github_repository_tracker.md
> +- For Issues:
```suggestion
For Issues:
```

2024-07-02 08:57 UTC, phazonoverload commented on Build A GitHub Repository Tracker With Directus Flow/github_repository_tracker.md
> +- For Issue comments:
```suggestion
For issue comments:
```

2024-07-02 08:57 UTC, phazonoverload commented on Build A GitHub Repository Tracker With Directus Flow/github_repository_tracker.md
> +- For pull requests:
```suggestion
For pull requests:
```

2024-07-02 08:57 UTC, phazonoverload commented on Build A GitHub Repository Tracker With Directus Flow/github_repository_tracker.md
> +Hi Sam,
```suggestion
Hi name,
```

2024-07-02 14:10 UTC, psalmuelle commented
Thank you @phazonoverload for your review. I have accepted them and fixed the bug on the email templates.

2024-07-08 15:56 UTC, phazonoverload reviewed
Thank you for writing this, and we are happy to consider it done in it's current state. My team will schedule it in to be published. 

This repo is just for authoring/reviewing - the actual piece will be published via a Directus project, so we'll take it from here. I'll close this issue to keep the main branch clean, but this is a acceptance of your work.

Could you email us at [devrel@directus.io](mailto:devrel@directus.io) and we'll share what we need to get you paid. Thanks!

2024-07-08 15:56 UTC, closed without merging