Integrating Melisearch Indexing in SolidStart and Directus
directus-labs/guest-authoring pull request #294
Opened 2024-07-11 16:09 UTC by Claradev32

This is the PR for the issue https://github.com/directus-labs/guest-authoring/issues/220

2024-07-25 12:25 UTC, phazonoverload reviewed
I'm looking to review this imminently, but could you please remove the SolidStart pieces as we agreed in the issue? I'm only interested in maintaining the index from Directus.

2024-07-25 14:47 UTC, Claradev32 commented
Hi @phazonoverload 
I have updated the draft to remove the SolidStart part. 

Thank you

2024-07-31 14:42 UTC, phazonoverload requested changes
Most suggestions are to bring this in line with the format of our existing Algolia post more closely. Once you accept them, we can accept this post 😄

2024-07-31 14:42 UTC, phazonoverload commented on integrating-melisearch-indexing-in-solidStart-and-directus/index.md
> +```
````suggestion
## Setting Up Meilisearch

Sign up for a Meilisearch account if you haven't already. Once you have your Meilisearch instance details, you will be able to copy your credentials in your dashboard. 

![Melisearch dashboard](<Screenshot 2024-07-11 at 06.45.38.png>)

Add the following environment variables to your project: 

```docker-compose
MEILISEARCH_HOST=your_meilisearch_host
MEILISEARCH_API_KEY=your_meilisearch_api_key
```

Navigate into your new extension directory, run `npm install meilisearch`, and then `npm run dev` to start the automatic extension building.

At the top of your extension's `src/index.js` file, initialize the Meilisearch client:

```javascript
import { MeiliSearch } from 'meilisearch'

const client = new MeiliSearch({
  host: process.env.MEILISEARCH_HOST,
  apiKey: process.env.MEILISEARCH_API_KEY
})
const index = client.index('directus_index')
```
````

2024-07-31 14:42 UTC, phazonoverload commented on integrating-melisearch-indexing-in-solidStart-and-directus/index.md
> +The `articles.items.create` action hook triggers after item creation. The `meta` object contains the new item's key (ID) and other fields in its payload property. By setting the `objectID` to the Dir
````suggestion
## Saving New Items to Index

Update your extension's exported function to process create events when a new `article` is added to the collection:

```javascript
export default ({ action }) => {
  action('articles.items.create', async (meta) => {
    await index.addDocuments([{ id: meta.key, ...meta.payload }])
  })
}
```

The `articles.items.create` action hook triggers after item creation. The `meta` object contains the new item's `key` (ID) and other fields in its `payload` property. By setting the `objectID` to the Directus item `id`, we ensure accurate referencing and management in Meilisearch.
````

2024-07-31 14:42 UTC, phazonoverload commented on integrating-melisearch-indexing-in-solidStart-and-directus/index.md
> +The `articles.items.update` action hook triggers when articles are updated. It receives `meta.keys` (an array of updated item IDs) and `meta.payload` (changed values). The hook updates each modified
````suggestion
### Updating Items in Index

Add another action hook to process updates when one or more articles are modified:

```javascript
action('articles.items.update', async (meta) => {
  await Promise.all(
    meta.keys.map(async (key) => 
      await index.updateDocuments([{ id: key, ...meta.payload }])
    )
  )
})
```

The `articles.items.update` action hook triggers when articles are updated. It receives `meta.keys` (an array of updated item IDs) and `meta.payload` (changed values). The hook updates each document in Meilisearch.
````

2024-07-31 14:42 UTC, phazonoverload commented on integrating-melisearch-indexing-in-solidStart-and-directus/index.md
> +![Melisearch with data from Directus](<Screenshot 2024-07-11 at 06.58.04.png>)
````suggestion
### Deleting Items in Index

Add an action hook to remove items from Meilisearch when they're deleted in Directus:

```javascript
action('articles.items.delete', async (meta) => {
  await index.deleteDocuments(meta.keys)
})
```

The `articles.items.delete` action hook triggers when articles are deleted. It receives `meta.keys`, an array of deleted item IDs. The hook uses these keys to remove the corresponding documents from the Meilisearch index.

Now add 3 items to your articles collection and you should see them in your Meilisearch index.

![Melisearch with data from Directus](<Screenshot 2024-07-11 at 06.58.04.png>)
````

2024-07-31 14:42 UTC, phazonoverload commented on integrating-melisearch-indexing-in-solidStart-and-directus/index.md
> +In this tutorial, you've learned how to integrate Meilisearch indexing with Directus and SolidStart. You've learned how to setup the Directus hooks that automatically indexes data created, updated, o
```suggestion
In this tutorial, you've learned how to integrate Meilisearch with Directus. You've learned how to setup the Directus hooks that automatically indexes data created, updated, or deleted from a Directus project in Meilisearch.
```

2024-07-31 14:47 UTC, Claradev32 commented
Alright, I have done that.

Thank you for the suggestions.

2024-07-31 20:26 UTC, phazonoverload commented
Thank you for writing this, and we are happy to consider it done in it's current state. My team will schedule it in to be published. 

This repo is just for authoring/reviewing - the actual piece will be published via a Directus project, so we'll take it from here. I'll close this issue to keep the main branch clean, but this is a acceptance of your work.

Could you email us at [devrel@directus.io](mailto:devrel@directus.io) and we'll share what we need to get you paid. Thanks!

2024-07-31 20:26 UTC, closed without merging