first draft
directus-labs/guest-authoring pull request #71
Opened 2024-01-24 07:30 UTC by davidmbochi

2024-02-15 06:10 UTC, davidmbochi commented
Okay. Thanks for the update.

2024-02-20 14:45 UTC, phazonoverload requested changes
Left some changes for you to make :)

2024-02-20 19:42 UTC, davidmbochi commented on directus-spring-boot/integrating spring boot in directus.md
> +- [IntelliJ IDEA community edition](https://www.jetbrains.com/idea/download/#section=linux) - Development environment for the Java programming language.
The IDE is usually provided for people not familiar with Java and don't know the IDE to use. However, we can remove it if the target is for Junior and senior developers.

2024-02-20 19:48 UTC, davidmbochi commented on directus-spring-boot/integrating spring boot in directus.md
> +## Project setup
Noted.

2024-02-21 05:59 UTC, davidmbochi commented on directus-spring-boot/integrating spring boot in directus.md
> +If you followed this steps to the latter, the project structure and dependencies of your application should be as shown below.
Sure

2024-02-21 06:07 UTC, davidmbochi commented on directus-spring-boot/integrating spring boot in directus.md
> +Having different packages in your application will help you to separate responsibilities, improve the readability of the code, and simplify making changes.
Noted

2024-02-21 06:32 UTC, davidmbochi commented on directus-spring-boot/integrating spring boot in directus.md
> +In this file, you have defined a class named `Article` with the fields `id`, `title`, `featuredImage`, and `body`. Note that this fields should be similar to those in your Directus project.
Okay.

2024-02-21 07:10 UTC, davidmbochi commented on directus-spring-boot/integrating spring boot in directus.md
> +
Okay.

2024-02-21 07:11 UTC, davidmbochi commented on directus-spring-boot/integrating spring boot in directus.md
> +```
Noted

2024-02-21 10:59 UTC, davidmbochi commented
Hi Kevin.

I have applied the requested changes. You can now review and let me know.

2024-02-26 10:49 UTC, phazonoverload commented on directus-spring-boot/integrating spring boot in directus.md
> +- [IntelliJ IDEA community edition](https://www.jetbrains.com/idea/download/#section=linux) - Development environment for the Java programming language.
And yes you're right if this was a beginner Java post, but we've already said they should have knowledge so it's safe to assume they have an IDE set up.

2024-02-26 10:50 UTC, phazonoverload approved these changes

2024-02-26 10:50 UTC, closed without merging

2024-02-26 10:50 UTC, phazonoverload commented
Thank you for writing this, and I'm happy to consider it done in it's current state. I'll schedule it in to be published. 

This repo is just for authoring/reviewing - the actual piece will be published via a Directus project, so I'll take it from here. I'll close this issue to keep the main branch clean, but this is a acceptance of your work.

Could you email me at [kevin@directus.io](mailto:kevin@directus.io) and I'll share what we need to get you paid.