first draft
directus-labs/guest-authoring pull request #74
Opened 2024-01-27 17:50 UTC by mizzleinetimi

2024-02-07 16:35 UTC, phazonoverload requested changes
I started reviewing this but have stopped because it does not follow the exact same format as our other guides. 

It should be: 
- Initialize Django Project (to the point of running dev server)
- Set up requests/env vars/anything needed to call Directus
- Using Global Metadata and Settings 
- Creating Pages With Directus 
- Creating Blog Posts With Directus 
  - Create Blog Post Listing
  - Create Blog Post Single
- Add Navigation

Please make it match this format: https://docs.directus.io/blog/getting-started-directus-and-eleventy-11ty-3

2024-02-07 16:35 UTC, phazonoverload commented on directus-django/integrating directus in django.md
> +#### Installing Django
Remove H4 - just go straight into the next step.

2024-02-07 16:35 UTC, phazonoverload commented on directus-django/integrating directus in django.md
> +## Project setup
```suggestion
## Create a Django Project
```

2024-02-07 16:35 UTC, phazonoverload commented on directus-django/integrating directus in django.md
> +This installs django within the virtual environment.
Remove this - it's repeating what you say before the command

2024-02-07 16:35 UTC, phazonoverload commented on directus-django/integrating directus in django.md
> +This command starts a new django project and loads up the boilerplate files within django
Again, remove - it's repeating what you've already said

2024-02-07 16:35 UTC, phazonoverload commented on directus-django/integrating directus in django.md
> +We need it to be able to make http requests to external API’s.
Remove

2024-02-07 16:35 UTC, phazonoverload commented on directus-django/integrating directus in django.md
> +This creates a new directory within our project containing all the necessary files for a django app
This isn't repeating what was before, but let's consolidate it with the previous sentence before the command.

2024-02-26 10:43 UTC, phazonoverload commented
Any update on this please?

2024-02-26 11:39 UTC, mizzleinetimi commented
Had a few setbacks. Will be ready on or before Thursday.

On Monday, February 26, 2024, Kevin Lewis ***@***.***> wrote:

> Any update on this please?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/directus-labs/guest-authoring/pull/74#issuecomment-1963820051>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALWRCCAJGU5RYGRMU22ZTK3YVRRMTAVCNFSM6AAAAABCNQOUI2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNRTHAZDAMBVGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-03-03 04:03 UTC, mizzleinetimi commented
Still working on this.

On Monday, February 26, 2024, omu inetimi ***@***.***> wrote:

> Had a few setbacks. Will be ready on or before Thursday.
>
> On Monday, February 26, 2024, Kevin Lewis ***@***.***>
> wrote:
>
>> Any update on this please?
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/directus-labs/guest-authoring/pull/74#issuecomment-1963820051>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ALWRCCAJGU5RYGRMU22ZTK3YVRRMTAVCNFSM6AAAAABCNQOUI2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNRTHAZDAMBVGE>
>> .
>> You are receiving this because you authored the thread.Message ID:
>> ***@***.***>
>>
>

2024-03-04 13:55 UTC, phazonoverload commented
Ok noted - it's been about a month since the initial review. I'm going to need amends made latest end of Thursday so I can review Friday. If that's not possible, let me know, but I may have to take it out of the content schedule

2024-03-22 18:07 UTC, phazonoverload requested changes
Added a couple of comments I need you to answer. I also would like you to be really explicit around where each file is meant to be placed -in what directories, etc. Every time you mention a new file, specify. 

There are some other small edits, but I'll handle those while publishing.

2024-03-26 13:18 UTC, mizzleinetimi commented on directus-django/integrating directus in django.md
> +Modify settings.py to include the necessary configurations for Directus API communication.
was a placeholder oversight on my end, updated the settings properly now.

2024-03-26 13:19 UTC, mizzleinetimi commented on directus-django/integrating directus in django.md
> +
done.

2024-03-26 13:20 UTC, mizzleinetimi commented
made all requested changes.

2024-04-03 08:58 UTC, phazonoverload approved these changes

2024-04-03 08:59 UTC, phazonoverload commented
Thank you for writing this, and I'm happy to consider it done in it's current state. I'll schedule it in to be published. 

This repo is just for authoring/reviewing - the actual piece will be published via a Directus project, so I'll take it from here. I'll close this issue to keep the main branch clean, but this is a acceptance of your work.

Could you email me at [kevin@directus.io](mailto:kevin@directus.io) and I'll share what we need to get you paid.

I'm very excited to publish this piece - it's very cool.

2024-04-03 08:59 UTC, closed without merging